version: '3.9'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'stock-service'
      MYSQL_USER: 'samuel'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      
volumes:
  my-db:
  db: